### ISSUE TITLE
yardstick-gridgain NoClassDefFoundError CacheDistributionMode using latest ignite snapshot

### ISSUE THREAD

**Issue by helpfull** [gridgain/yardstick-gridgain#1]
I get This Exception running the Yardstick bench mark agenst the latest version of Ignite 1.4.1-SNAPSHOT   the default version of ignite works 

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/ignite/internal/processors/cache/CacheDistributionMode
    at org.apache.ignite.yardstick.IgniteBenchmarkArguments.<init>(IgniteBenchmarkArguments.java:47)
    at org.apache.ignite.yardstick.IgniteNode.start(IgniteNode.java:47)
    at org.yardstickframework.BenchmarkServerStartUp.main(BenchmarkServerStartUp.java:61)
Caused by: java.lang.ClassNotFoundException: org.apache.ignite.internal.processors.cache.CacheDistributionMode
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 3 more

```

I am removing the default ignite jars from yardstick-ignite/libs

 'rm yardstick-ignite/libs/ignite-aws*' 
 'rm yardstick-ignite/libs/ignite-core*' 
 'rm yardstick-ignite/libs/ignite-indexing*' 
 'rm yardstick-ignite/libs/ignite-spring*' 

and replacing them with the ignite jars from my local .m2 repo 

 cp $(find ~/.m2 -name ignite-aws-${version}.jar) yardstick-ignite/libs
 cp $(find ~/.m2 -name ignite-core-${version}.jar) yardstick-ignite/libs
 cp $(find ~/.m2 -name ignite-indexing-${version}.jar) yardstick-ignite/libs
 cp $(find ~/.m2 -name ignite-spring-${version}.jar) yardstick-ignite/libs

the result is the latest ignite jars copyed up to all the hotest running the test,  "servers" and driver hosts 

ls yardstick-ignite/libs/ignite*.jar
yardstick-ignite/libs/ignite-aws-1.4.1-SNAPSHOT.jar
yardstick-ignite/libs/ignite-core-1.4.1-SNAPSHOT.jar
yardstick-ignite/libs/ignite-indexing-1.4.1-SNAPSHOT.jar
yardstick-ignite/libs/ignite-spring-1.4.1-SNAPSHOT.jar
yardstick-ignite/libs/ignite-yardstick-0.1.0.jar


I am using the latest version of  yardstick-ignite  running agents the latest version of Ignite
```

**Comment by helpfull** [comment]
I just see this is the wrong repo, but any way i could not open an issue vs 
https://github.com/yardstick-benchmarks/yardstick-ignite

**Comment by helpfull** [comment]
or maybe I should open the issue with 
https://github.com/gridgain/yardstick

or at  https://github.com/gridgain/incubator-ignite
which also looks to be closed to issues

**Comment by ntikhonov** [comment]
Hello!
You could to use this repo (https://github.com/apacheignite/yardstick-ignite) for Apache Ignite. Sorry for delay!
